---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: crunchydata
  namespace: flux-system
spec:
  type: oci
  interval: 5m
  url: oci://registry.developers.crunchydata.com/crunchydata
