---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2beta2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: jellyfin
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.0.4
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  dependsOn:
    - name: rook-ceph-cluster
      namespace: rook-ceph
  values:
    controllers:
      jellyfin:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: jellyfin/jellyfin
              tag: "2024120905"
            env:
              TZ: America/New_York
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    port: 8096
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 100m
              limits:
                memory: 16Gi
    service:
      app:
        controller: jellyfin
        type: LoadBalancer
        annotations:
          io.cilium/lb-ipam-ips: 192.168.51.181
        ports:
          http:
            port: 8096
    persistence:
      config:
        accessMode: ReadWriteOnce
        type: persistentVolumeClaim
        enabled: true
        size: 50Gi
        storageClass: ceph-rbd
        advancedMounts:
          jellyfin:
            app:
              - path: /config
      cache:
        accessMode: ReadWriteOnce
        type: persistentVolumeClaim
        enabled: true
        size: 10Gi
        storageClass: ceph-rbd
        advancedMounts:
          jellyfin:
            app:
              - path: /cache
      media:
        type: nfs
        server: 192.168.51.191
        path: /mnt/pool-01/media
        globalMounts:
          - path: /mnt/media
            readOnly: true
