---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-proton-bridge
  namespace: flux-system
spec:
  path: ./kubernetes/apps/selfhosted/proton-bridge/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: proton-bridge
      namespace: selfhosted
  interval: 30m
  retryInterval: 1m
  timeout: 3m
