---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: proton-bridge
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      chart: protonmail-bridge
      version: 5.4.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    image:
      repository: shenxn/protonmail-bridge
      tag: 3.12.0-1
    env:
      TZ: America/New_York
    service:
      main:
        type: LoadBalancer
        ports:
          http:
            enabled: false
          smtp:
            enabled: true
            protocol: TCP
            port: 25
          imap:
            enabled: true
            protocol: TCP
            port: 143
    persistence:
      config:
        enabled: true
        mountPath: /root
        size: 5Gi
