---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-site2
  target:
    name: grafana-secret
    template:
      engineVersion: v2
      data:
        GF_DATABASE_NAME: &dbName grafana
        GF_DATABASE_HOST: postgres16-rw.database.svc.cluster.local:5432
        GF_DATABASE_USER: &dbUser "{{ .GRAFANA_POSTGRES_USER }}"
        GF_DATABASE_PASSWORD: &dbPass "{{ .GRAFANA_POSTGRES_PASS }}"
        GF_DATABASE_SSL_MODE: disable
        GF_DATABASE_TYPE: postgres
        INIT_POSTGRES_DBNAME: *dbName
        INIT_POSTGRES_HOST: postgres16-rw.database.svc.cluster.local
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: GRAFANA
