---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: unifi-controller
spec:
  interval: 30m
  chart:
    spec:
      chart: unifi-controller
      version: 2.6.1
      sourceRef:
        kind: HelmRepository
        name: qonstrukt
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    image:
      repository: linuxserver/unifi-controller
      tag: 8.0.24
    environment:
      timezone: "America/Toronto"
      uid: 1000
      gid: 1000
    service:
      type: "LoadBalancer"
      annotations: {}
      ports:
        devicecom: 8080
        webapi: 8443
      appDiscovery: false
      syslogCapture: false
      loadBalancerIP: "192.168.51.216"
    ingress:
      enabled: true
      className: internal
      annotations:
        nginx.ingress.kubernetes.io/backend-protocol: HTTPS
      hosts:
        - host: &host unifi.${SECRET_DOMAIN}
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls:
        - hosts:
            - *host
    persistence:
      enabled: true
      accessMode: ReadWriteOnce 
      size: 8Gi 
      storageClass: ceph-rbd
      backup:
        enabled: true
        accessMode: ReadWriteOnce 
        size: 8Gi 
        storageClass: ceph-rbd
