---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: crunchy-postgres-operator
spec:
  interval: 30m
  chart:
    spec:
      chart: pgo
      version: 5.5.1
      sourceRef:
        kind: HelmRepository
        name: crunchydata
        namespace: flux-system
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    crds: CreateReplace
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  dependsOn:
    - name: rook-ceph
      namespace: rook-ceph
    - name: rook-ceph-cluster
      namespace: rook-ceph
  values:
    install:
      clusterLabels:
        app.kubernetes.io/name: pgo
