---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudnative-pg
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-site2
  target:
    name: cloudnative-pg-secret
    template:
      engineVersion: v2
      metadata:
        labels:
          cnpg.io/reload: "true"
  data:
    - secretKey: username
      remoteRef:
        key: POSTGRES_SUPER_USER
    - secretKey: password
      remoteRef:
        key: POSTGRES_SUPER_PASS
    - secretKey: aws-access-key-id
      remoteRef:
        key: MINIO_ACCESS_KEY_ID
    - secretKey: aws-secret-access-key
      remoteRef:
        key: MINIO_SECRET_ACCESS_KEY
