---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: crunchy-pgo
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-site2
  target:
    name: crunchy-pgo-secret
    template:
      engineVersion: v2
      data:
        s3.conf: |
          [global]
          repo1-s3-key={{ .MINIO_ACCESS_KEY_ID }}
          repo1-s3-key-secret={{ .MINIO_SECRET_ACCESS_KEY }}
        encryption.conf: |
          [global]
          repo1-cipher-pass={{ .CRUNCHY_PGO_CIPHER_PASS }}
  dataFrom:
    - extract:
        key: MINIO
    - extract:
        key: CRUNCHY_PGO
