---
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: json-exporter
spec:
  staticConfigs:
    - targets:
        - http://ams.private.cloud:5080/WebRTCAppEE/rest/v2/broadcasts/list/0/9999
  metricsPath: /probe
  scrape_interval: 15s
  relabel_configs:
    - source_labels: [__address__]
      target_label: __param_target
    - source_labels: [__param_target]
      target_label: instance
    - target_label: __address__
      replacement: ams.private.cloud:7979
